### ISSUE TITLE
Does not seem to work.. :)

### ISSUE THREAD

**Issue by jaybabani** [felippe-regazio/php-hot-reloader#11]
Followed all the mentioned steps, but not working.

Even example.php is not working

**Comment by felippe-regazio** [comment]
Hello jaybabani. There is something on the console? Could you please paste here?
How are you accessing the example? Directly on the browser? Please, paste your URL either.

Thank you.

**Comment by jlenik** [comment]
I am kinda hoping that's the same issue I encountered - the usual windows headache - slashes escape characters, check my pull request, thanks. 

#12

**Comment by felippe-regazio** [comment]
Thats pretty cool @jlenik, thank you. After a local test, i merged your PR. It makes total sense since windows slashes are also a escape char. Im also kinda hoping thats the same issue : )

**Comment by jlenik** [comment]
Thanks. It's the first hot reload that seems to work for me for php and it's pretty hassle free. There are few more things that bother me, but the other one related to this "does not seem to work" issue is that it takes a lot of time to update on large projects. Maybe add vendors folder to "IGNORE" by default? Or at least suggest it.

**Comment by felippe-regazio** [comment]
A default ignore list could be something cool. Would be great to write a better diff algorithm too. Im thinking about integrate with git to track files. So, the files on the watch list would be also the result of a git status. Feel free to open issues just to suggest improvement points.

**Comment by felippe-regazio** [comment]
@jlenik i added an experimental "git mode". If you dont mind in testing, just update your php-hot-reloader then in your phrwatcher you must set your $WATCH variable to:

```php
$WATCH = "git:repositoy_path";
```

Where repository path is problem your project root. If you keep your phrwatcher on your project root, you can do

```php
$WATCH = "git:" . __DIR__;
```

Even if you dont keep the phrfile on project root you can use the strategy above, but git wont track the __DIR__ parent dirs, only children.

Now the Reloader must watch only the Modified files in git file tree. The Watcher file list is automatically updated as git tracks the files. I think this will increase the diff speed : )

**Comment by jlenik** [comment]
It's one of the first times that I realized why devs hate Windows so much, so I'll get back to you later, but quick question - what is the idea behind this part, what use case does it solve?
`$DS = !strpos($this->ROOT, DIRECTORY_SEPARATOR) == strlen($this->ROOT) ? DIRECTORY_SEPARATOR : "";
`
It's`` from diff checker.

**Comment by jlenik** [comment]
Ok, lots of issues for such a small feature, but I made it work for me. Feel free to review and edit #13

**Comment by felippe-regazio** [comment]
@jlenik The line that you mentioned just adds a trailing slash in case it doesnt exists. If has trailling slash $DS = "", else $DS = DIRECTORY_SEPARATOR. So the line below wont break:

```
$ignore = $this->ROOT.$DS.$ignore;
```

Ill review your PR, many thanks again. Your contribution has been very productive!

**Comment by felippe-regazio** [comment]
@jlenik I closed your PR, but implemented all your solutions. I closed because i used another solution to the $DS problem. In fact, i removed the DS, and the ROOT is validaded (if there is no trailling slash, will be added on the constructor). I also added the git mode to the docs. Hope it works now : )
