### ISSUE TITLE
Infinite loop?

### ISSUE THREAD

**Issue by XGhozt** [felippe-regazio/php-hot-reloader#2]
I tried to use this on an older (large) project and it seemed like it conflicted with some jQuery code or other libraries (not sure). I was using it on a local dev server (vagrant) and the console was showing hundreds of requests per second (reloading the page?) and some errors.

It seemed to sort of work, but after the first reload it just stopped working because the server was overloaded from refreshing every single included file non-stop.

Edit: It might be because this requires ES6 javascript and my project is not ES6.

**Comment by felippe-regazio** [comment]
interesting. lets analyze : )

are you using any backend framework?
could you provide a ctrl+v or a print of the errors?
what browser are you using?

sometimes, when dealing with large projects, the tracker must trying to watch some dynamic or temp file, and then it goes crazy because some of those files can be created and deleted many times in a couple minutes. we can easily solve it adding this temp/dynamic files/folders to the ignoring array. but its a just a guess. better see the info first.

**Comment by axelrindle** [comment]
A solution to this issue could be using a WebSocket connection instead of having a memory intensive loop.

**Comment by XGhozt** [comment]
Haven't tried again since the first time. But maybe I can shed SOME light. I don't remember the console errors other then the ones failing because the little vagrant server was at 100% CPU. Not using any frameworks (crazy I know). This was in Firefox.

**Comment by felippe-regazio** [comment]
Im gonna take a look this weekend. Think the @axelrindle has a good point with the socket. I think is also possible to watch the assets with JS observers instead sockets or loopings. I just dont knew it at the time of this project. 

Im thinking about the possibility of rewrite the live.js using observers for the assets and sockets for the backend file changes. It will be great.

Ill keep you aware on this issue.

**Comment by felippe-regazio** [comment]
I started to rewrite the php hot reloader this week. Must be ok very soon. Here is the approach:

I'll open a dynamic built in server.
The server will run a watcher with your configuration.
This server answer with a json containing a message.
The client will keep pinging the server and will execute the given messages.

Let me know if you guys have some considerations.
I'll create a branch today if the source progress.

**Comment by felippe-regazio** [comment]
Hello @XGhozt  i rewrote the entire tool. It uses a totally different approach now (using SSE).
Could you please update your Reloader version and give a try? Think it will fit well for your app.

o/
