### ISSUE TITLE
Can't make this work with Wordpress

### ISSUE THREAD

**Issue by WideCircle** [felippe-regazio/php-hot-reloader#5]
Hi there!
I get an "Fatal error: Uncaught Error: Class..." when I try to use this in a wordpress environment. I've succeeded to require the php-file/class.
But as soon as I write this: 
`$reloader = new HotReloader();` I get the error message...

Can't figure out what I'm doing wrong...

Best, Niklas

**Comment by felippe-regazio** [comment]
Hey Niklas, thanks for your feedback.
How did you installed? Composer or manual?
Can you past the entire error message please?

Thank you.

**Comment by LeviD77** [comment]
Hey there! Wordpress handles the namespace differently. Just delete the `namespace HotRelader;` from the HotReloader.php file! :)

**Comment by felippe-regazio** [comment]
Thanks for the quick tip @LeviD77, gonna write a fix for that.

**Comment by WideCircle** [comment]
Aha - thanks to both of you.
@LeviD77 , @felippe-regazio 

I will check this out!!

Sorry for my late answer...

**Comment by felippe-regazio** [comment]
@WideCircle a new version of this Reloader is available.
It was entirely re wroted, could you give a try?

It uses a totally different approach and i think it will fit well with wordpress.
