### ISSUE TITLE
JS changes to the DOM cause a reload

### ISSUE THREAD

**Issue by perronuk** [felippe-regazio/php-hot-reloader#6]
Your code works perfectly for JS/CSS changes and for uploaded changes to the PHP/HTML.

However it also reloads (via the innerHTML replacement) even when a Javascript makes changes to the DOM, such as image sliders. This immediately erases those JS DOM changes, so breaks any JS generated elements.

Can this be fixed to only reload the innerHTML when the PHP/HTML has been changed by an upload, and not by a script?

[ideally it would need to re-fire those scripts after replacing with the new HTML too]

**Comment by felippe-regazio** [comment]
Hey @perronuk. Im rewriting this script, also rewriting the JS part. Im going slow cause my son was born just a few months ago and has been a lot of home work since then ;P Anyway, hope to release a new version at the end of december, so ill include your issue on the TODO.

**Comment by felippe-regazio** [comment]
Hey @perronuk  how are you? Sorry for the long time.
A new release of this tool is available now, and it solves your problem.

Could you please update your Hot Reloader Version?
